### ISSUE TITLE
Is the correct kitura version installed?

### ISSUE THREAD

**Issue by agreensh** [IBM/FoodTrackerBackend#10]
When I do "brew install kitura", then "kitura -V" gives version 0.0.8. Is that correct?

"kitura init" then gives

/usr/local/Cellar/kitura/0.0.8/libexec/lib/node_modules/kitura-cli/kitura-init.js:6
let args = process.argv.slice(2);
    ^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

What am I missing?

**Comment by seabaylea** [comment]
Hi @agreensh yes, that's the latest version of the Kitura CLI. My guess is that there was a problem during the `brew install kitura` step. If `brew` has problems it usually writes a suggested solution to the console (which then unfortunately tends to scroll off the screen). 

Could you try running `brew doctor` and see if it reports any issues?

**Comment by seabaylea** [comment]
Hi @agreensh Have you had a chance to take another look at this?

**Comment by agreensh** [comment]
Not yet. Will let you know if I still have problems.

Thanks,
Andy

**Comment by seabaylea** [comment]
Closing as this is now a few months old. Please re-open if needed.

**Comment by AnYuan** [comment]
Same issue here,
Below command solved the problem:
0) brew uninstall node
1) brew install node
3) brew link --overwrite node
Hope to help

**Comment by jfgrang** [comment]
@AnYuan you did
