### ISSUE TITLE
generate-xcodeproj failed

### ISSUE THREAD

**Issue by t3ta** [IBM/FoodTrackerBackend#23]
Hi.
I tried connecting FoodServer to PostgreSQL as per the README.
I received error when executing following command.
```
$ swift package generate-xcodeproj
error: product dependency 'Configuration' not found
```
I added the line `.package(url: "https://github.com/IBM-Swift/Configuration.git", .upToNextMajor(from: "3.0.0")),` below the line `.package(url: "https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL.git", .upToNextMinor(from: "1.1.0")),` and .xcodeproj was generated.
Did I skip the procedure somewhere?

**Comment by seabaylea** [comment]
No - you did everything right. The instructions are incorrectly asking you to add "Configuration" as as dependency of the "Application" target in the Package.swift file when you don't need to.

**Comment by seabaylea** [comment]
FYI, the following PR should update the README.md to fix it:
https://github.com/IBM/FoodTrackerBackend/pull/22

**Comment by t3ta** [comment]
Oh, I should have watched the PR...
Thank you for your immediate reply!
