### ISSUE TITLE
The plist file doesn't exist

### ISSUE THREAD

**Issue by redwards72git** [IBM/FoodTrackerBackend#37]
[!] The plist file at path `/Users/.../FoodTrackerBackend/iOS/FoodTracker/FoodTracker.xcodeproj/project.pbxproj` doesn't exist.

**Comment by mludi** [comment]
Yeah, I've the same issue on `pod install`

**Comment by seabaylea** [comment]
@Andrew-Lees11 could you take a look at this?

**Comment by Andrew-Lees11** [comment]
Hello @mludi 
When i test this Pod install is working for KituraKit. 
What is your package path and would you be able to paste your podfile here?

Would you be able to rerun the Cocoapods part for me to see you if still get the issue?
```
git clone http://github.com/IBM/FoodTrackerBackend
cd FoodTrackerBackend/iOS/FoodTracker
pod init
open Podfile
platform :ios, '11.0'
pod 'KituraKit'
pod install
open FoodTracker.xcworkspace
```

**Comment by mludi** [comment]
Hi @Andrew-Lees11, I use the branch `CompletedFoodTracker`

This is the Podfile

```
# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'FoodTracker' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodTracker
  pod 'KituraKit', :git => 'https://github.com/IBM-Swift/KituraKit.git', :branch => 'pod'

  target 'FoodTrackerTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by mludi** [comment]
Thanks! I hadn't the time to figure it out.

**Comment by Andrew-Lees11** [comment]
So the project.pbxproj was missing from the completed foodtracker. I have raised a PR that should fix it. For now you can use [my fork](https://github.com/Andrew-Lees11/FoodTrackerBackend/tree/CompletedFoodTracker) to confirm that this should fix the issue.

**Comment by mludi** [comment]
Yeah, that did it!
Thanks @Andrew-Lees11 🎉

**Comment by ianpartridge** [comment]
Thanks @Andrew-Lees11 !

**Comment by jackieoh1** [comment]
> I have raised a PR that should fix it.

I'm sorry - this makes no sense to me.  Can you please tell me how to solve the issue of this nonexistent file?  I went to the fork.  I saw no solution to it.  Thank you.

**Comment by seabaylea** [comment]
@jackieoh1 The `project.pbxproj` file that was reported missing was added to the CompletedFoodTracker branch - which you can see here:
https://github.com/IBM/FoodTrackerBackend/blob/CompletedFoodTracker/iOS/FoodTracker/FoodTracker.xcodeproj/project.pbxproj
