### ISSUE TITLE
Missing FoodServer.xcodeproj in 2.2

### ISSUE THREAD

**Issue by gerriet** [IBM/FoodTrackerBackend#6]
kitura init does not create an xcodeproj (at least for me) in the FoodServer-directory, that I could open.

**Comment by LarsJK** [comment]
I had problems with `kitura init` failing..
Intalling yeoman globally worked for me.. `npm install -g yo`

**Comment by gerriet** [comment]
@LarsJK Thanks for the suggestion. I tried but it did not solve my problem. But now I see the error message from kitura init, seemingly related to my gcc-configuration. I will close this issue here as it is not specific for this project.
